class_name BroadcastWaves
extends RefCounted
## Versioned expanded campaign; old checkpoint waves remain in EncounterWaves.
const MISSIONS: Dictionary = {
	1: [
		preload("res://content/encounters/waves/m01_w01.tres"),
		preload("res://content/encounters/waves/m01_w02.tres"),
		preload("res://content/encounters/waves/m01_w03.tres"),
		preload("res://content/encounters/waves/m01_w04.tres"),
		preload("res://content/encounters/waves/m01_w05.tres"),
		preload("res://content/encounters/waves/m01_w06.tres"),
		preload("res://content/encounters/waves/m01_w07.tres"),
		preload("res://content/encounters/waves/m01_w08.tres"),
		preload("res://content/encounters/waves/m01_w09.tres"),
		preload("res://content/encounters/waves/m01_w10.tres"),
	],
	2: [
		preload("res://content/encounters/waves/m02_w01.tres"),
		preload("res://content/encounters/waves/m02_w02.tres"),
		preload("res://content/encounters/waves/m02_w03.tres"),
		preload("res://content/encounters/waves/m02_w04.tres"),
		preload("res://content/encounters/waves/m02_w05.tres"),
		preload("res://content/encounters/waves/m02_w06.tres"),
		preload("res://content/encounters/waves/m02_w07.tres"),
		preload("res://content/encounters/waves/m02_w08.tres"),
		preload("res://content/encounters/waves/m02_w09.tres"),
		preload("res://content/encounters/waves/m02_w10.tres"),
	],
	3: [
		preload("res://content/encounters/waves/m03_w01.tres"),
		preload("res://content/encounters/waves/m03_w02.tres"),
		preload("res://content/encounters/waves/m03_w03.tres"),
		preload("res://content/encounters/waves/m03_w04.tres"),
		preload("res://content/encounters/waves/m03_w05.tres"),
		preload("res://content/encounters/waves/m03_w06.tres"),
		preload("res://content/encounters/waves/m03_w07.tres"),
		preload("res://content/encounters/waves/m03_w08.tres"),
		preload("res://content/encounters/waves/m03_w09.tres"),
		preload("res://content/encounters/waves/m03_w10.tres"),
	],
	4: [
		preload("res://content/broadcast/waves/m04_w01.tres"),
		preload("res://content/broadcast/waves/m04_w02.tres"),
		preload("res://content/broadcast/waves/m04_w03.tres"),
		preload("res://content/broadcast/waves/m04_w04.tres"),
		preload("res://content/broadcast/waves/m04_w05.tres"),
		preload("res://content/broadcast/waves/m04_w06.tres"),
		preload("res://content/broadcast/waves/m04_w07.tres"),
		preload("res://content/broadcast/waves/m04_w08.tres"),
		preload("res://content/broadcast/waves/m04_w09.tres"),
		preload("res://content/broadcast/waves/m04_w10.tres"),
	],
	5: [
		preload("res://content/broadcast/waves/m05_w01.tres"),
		preload("res://content/broadcast/waves/m05_w02.tres"),
		preload("res://content/broadcast/waves/m05_w03.tres"),
		preload("res://content/broadcast/waves/m05_w04.tres"),
		preload("res://content/broadcast/waves/m05_w05.tres"),
		preload("res://content/broadcast/waves/m05_w06.tres"),
		preload("res://content/broadcast/waves/m05_w07.tres"),
		preload("res://content/broadcast/waves/m05_w08.tres"),
		preload("res://content/broadcast/waves/m05_w09.tres"),
		preload("res://content/broadcast/waves/m05_w10.tres"),
	],
	6: [
		preload("res://content/broadcast/waves/m06_w01.tres"),
		preload("res://content/broadcast/waves/m06_w02.tres"),
		preload("res://content/broadcast/waves/m06_w03.tres"),
		preload("res://content/broadcast/waves/m06_w04.tres"),
		preload("res://content/broadcast/waves/m06_w05.tres"),
		preload("res://content/broadcast/waves/m06_w06.tres"),
		preload("res://content/broadcast/waves/m06_w07.tres"),
		preload("res://content/broadcast/waves/m06_w08.tres"),
		preload("res://content/broadcast/waves/m06_w09.tres"),
		preload("res://content/broadcast/waves/m06_w10.tres"),
	],
	7: [
		preload("res://content/broadcast/waves/m07_w01.tres"),
		preload("res://content/broadcast/waves/m07_w02.tres"),
		preload("res://content/broadcast/waves/m07_w03.tres"),
		preload("res://content/broadcast/waves/m07_w04.tres"),
		preload("res://content/broadcast/waves/m07_w05.tres"),
		preload("res://content/broadcast/waves/m07_w06.tres"),
		preload("res://content/broadcast/waves/m07_w07.tres"),
		preload("res://content/broadcast/waves/m07_w08.tres"),
		preload("res://content/broadcast/waves/m07_w09.tres"),
		preload("res://content/broadcast/waves/m07_w10.tres"),
	],
	8: [
		preload("res://content/broadcast/waves/m08_w01.tres"),
		preload("res://content/broadcast/waves/m08_w02.tres"),
		preload("res://content/broadcast/waves/m08_w03.tres"),
		preload("res://content/broadcast/waves/m08_w04.tres"),
		preload("res://content/broadcast/waves/m08_w05.tres"),
		preload("res://content/broadcast/waves/m08_w06.tres"),
		preload("res://content/broadcast/waves/m08_w07.tres"),
		preload("res://content/broadcast/waves/m08_w08.tres"),
		preload("res://content/broadcast/waves/m08_w09.tres"),
		preload("res://content/broadcast/waves/m08_w10.tres"),
	],
	9: [
		preload("res://content/broadcast/waves/m09_w01.tres"),
		preload("res://content/broadcast/waves/m09_w02.tres"),
		preload("res://content/broadcast/waves/m09_w03.tres"),
		preload("res://content/broadcast/waves/m09_w04.tres"),
		preload("res://content/broadcast/waves/m09_w05.tres"),
		preload("res://content/broadcast/waves/m09_w06.tres"),
		preload("res://content/broadcast/waves/m09_w07.tres"),
		preload("res://content/broadcast/waves/m09_w08.tres"),
		preload("res://content/broadcast/waves/m09_w09.tres"),
		preload("res://content/broadcast/waves/m09_w10.tres"),
	],
	10: [
		preload("res://content/broadcast/waves/m10_w01.tres"),
		preload("res://content/broadcast/waves/m10_w02.tres"),
		preload("res://content/broadcast/waves/m10_w03.tres"),
		preload("res://content/broadcast/waves/m10_w04.tres"),
		preload("res://content/broadcast/waves/m10_w05.tres"),
		preload("res://content/broadcast/waves/m10_w06.tres"),
		preload("res://content/broadcast/waves/m10_w07.tres"),
		preload("res://content/broadcast/waves/m10_w08.tres"),
		preload("res://content/broadcast/waves/m10_w09.tres"),
		preload("res://content/broadcast/waves/m10_w10.tres"),
	],
	11: [
		preload("res://content/broadcast/waves/m11_w01.tres"),
		preload("res://content/broadcast/waves/m11_w02.tres"),
		preload("res://content/broadcast/waves/m11_w03.tres"),
		preload("res://content/broadcast/waves/m11_w04.tres"),
		preload("res://content/broadcast/waves/m11_w05.tres"),
		preload("res://content/broadcast/waves/m11_w06.tres"),
		preload("res://content/broadcast/waves/m11_w07.tres"),
		preload("res://content/broadcast/waves/m11_w08.tres"),
		preload("res://content/broadcast/waves/m11_w09.tres"),
		preload("res://content/broadcast/waves/m11_w10.tres"),
	],
	12: [
		preload("res://content/broadcast/waves/m12_w01.tres"),
		preload("res://content/broadcast/waves/m12_w02.tres"),
		preload("res://content/broadcast/waves/m12_w03.tres"),
		preload("res://content/broadcast/waves/m12_w04.tres"),
		preload("res://content/broadcast/waves/m12_w05.tres"),
		preload("res://content/broadcast/waves/m12_w06.tres"),
		preload("res://content/broadcast/waves/m12_w07.tres"),
		preload("res://content/broadcast/waves/m12_w08.tres"),
		preload("res://content/broadcast/waves/m12_w09.tres"),
		preload("res://content/broadcast/waves/m12_w10.tres"),
	],
}
