class_name EncounterWaves
extends RefCounted
## Generated by tools/generate_encounter_content.py.
const MISSIONS: Dictionary = {
	1: [
		preload("res://content/encounters/waves/m01_w01.tres"),
		preload("res://content/encounters/waves/m01_w02.tres"),
		preload("res://content/encounters/waves/m01_w03.tres"),
		preload("res://content/encounters/waves/m01_w04.tres"),
		preload("res://content/encounters/waves/m01_w05.tres"),
		preload("res://content/encounters/waves/m01_w06.tres"),
		preload("res://content/encounters/waves/m01_w07.tres"),
		preload("res://content/encounters/waves/m01_w08.tres"),
		preload("res://content/encounters/waves/m01_w09.tres"),
		preload("res://content/encounters/waves/m01_w10.tres"),
	],
	2: [
		preload("res://content/encounters/waves/m02_w01.tres"),
		preload("res://content/encounters/waves/m02_w02.tres"),
		preload("res://content/encounters/waves/m02_w03.tres"),
		preload("res://content/encounters/waves/m02_w04.tres"),
		preload("res://content/encounters/waves/m02_w05.tres"),
		preload("res://content/encounters/waves/m02_w06.tres"),
		preload("res://content/encounters/waves/m02_w07.tres"),
		preload("res://content/encounters/waves/m02_w08.tres"),
		preload("res://content/encounters/waves/m02_w09.tres"),
		preload("res://content/encounters/waves/m02_w10.tres"),
	],
	3: [
		preload("res://content/encounters/waves/m03_w01.tres"),
		preload("res://content/encounters/waves/m03_w02.tres"),
		preload("res://content/encounters/waves/m03_w03.tres"),
		preload("res://content/encounters/waves/m03_w04.tres"),
		preload("res://content/encounters/waves/m03_w05.tres"),
		preload("res://content/encounters/waves/m03_w06.tres"),
		preload("res://content/encounters/waves/m03_w07.tres"),
		preload("res://content/encounters/waves/m03_w08.tres"),
		preload("res://content/encounters/waves/m03_w09.tres"),
		preload("res://content/encounters/waves/m03_w10.tres"),
	],
}
