#!/usr/bin/env python3
"""M8 opening increment: three authored missions; deterministic, bounded content."""
from pathlib import Path
import csv
import io

ROOT = Path(__file__).resolve().parents[1]
STRINGS = {}
S, D, C = 'm2.swarmer', 'm2.diver', 'm2.carrier'
ELITES = ['m8.elite_swarmer', 'm8.elite_carrier', 'm8.elite_diver']
TITLES = ['First Transmission', 'Carrier Traffic', 'Crossed Wires']
BRIEFS = [
    'Tight swarms give way to alternating lanes. Aim Burst into groups; focus divers with dive markers before they accelerate. Gold-ring elites appear in wave 6 before the finale.',
    'Carriers travel with escorts and release at most three swarmers and three destructible bolts. Focus the carrier early or intercept its bolts. Elite carriers appear in wave 6.',
    'Divers cross between swarm lanes while carriers hold the center. Watch the dive markers, switch focus, and save Burst for clustered threats. Elite divers appear in wave 6.',
]

def write_resource(path, kind, ident, key, fields):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f'''[gd_resource type="Resource" script_class="{kind}" load_steps=2 format=3]
[ext_resource type="Script" path="res://scripts/core/definitions/{'enemy' if kind == 'EnemyDefinition' else 'wave' if kind == 'WaveDefinition' else 'mission'}_definition.gd" id="1"]
[resource]
script = ExtResource("1")
id = &"{ident}"
name_key = &"{key}"
description_key = &"{key}_DESC"
{fields}
''')

def names(ids):
    return 'Array[StringName]([' + ', '.join('&"' + x + '"' for x in ids) + '])'

def generate():
    # Elites keep their family's tells and counters. No new finale-only mechanic.
    for family, health, speed, radius, breach, path in [
        ('swarmer', 42., 48., 23., 18., 0),
        ('carrier', 115., 26., 34., 36., 2),
        ('diver', 52., 43., 26., 26., 1),
    ]:
        key = 'M8_ELITE_' + family.upper()
        STRINGS[key] = 'Elite ' + family.title()
        STRINGS[key + '_DESC'] = 'Gold-ring veteran: more health, familiar attack tells and counters.'
        fields = f'elite = true\nhealth = {health}\nspeed = {speed}\nradius = {radius}\nbreach_damage = {breach}\npath_kind = {path}'
        if family == 'carrier':
            fields += '\nchild_id = &"m2.swarmer"\nchild_limit = 3\nprojectile_limit = 3\nability_interval = 3.0'
        write_resource(ROOT / f'content/encounters/enemies/elite_{family}.tres', 'EnemyDefinition', 'm8.elite_' + family, key, fields)
    for mission in range(1, 4):
        wave_ids = []
        for wave in range(1, 11):
            # Different group shapes, density, tempo, and family sequencing per mission.
            if mission == 1:
                group = [S] * 5 if wave < 3 else [S, S, D if wave % 2 else S, S, S]
                formation = 0 if wave <= 3 else 1 if wave <= 7 else 2
                interval = 6.4 if wave < 4 else 5.8
                groups = 7 + wave // 3
            elif mission == 2:
                group = [S, C, S] if wave <= 3 else [S, S, C, S, D if wave >= 5 else S]
                formation = 3
                interval = 7.2 if wave < 4 else 6.4
                groups = 7 + wave // 4
            else:
                group = [S, D, S, D, S] if wave % 2 else [S, C, S, D, S]
                formation = 1 if wave % 2 else 2
                interval = 6.2
                groups = 8 + wave // 4
            enemies = group * groups
            if wave in [6, 8, 9, 10]:
                # Introduce one veteran before escalating to a spaced finale trio.
                for index in ([0, len(group) * 3, len(group) * 6] if wave == 10 else [0]):
                    enemies[index] = ELITES[mission - 1]
            ident = f'm8.m{mission:02}.w{wave:02}'
            key = f'M8_M{mission}_W{wave}'
            STRINGS[key] = f'{TITLES[mission - 1]} · Wave {wave}'
            STRINGS[key + '_DESC'] = BRIEFS[mission - 1]
            write_resource(ROOT / f'content/encounters/waves/m{mission:02}_w{wave:02}.tres', 'WaveDefinition', ident, key,
                           f'spawn_interval = {interval}\ngroup_size = {len(group)}\nformation = {formation}\nenemy_ids = {names(enemies)}')
            wave_ids.append(ident)
        key = f'M7_MISSION_{mission}'
        STRINGS[key] = f'Rooftops {mission} · {TITLES[mission - 1]}'
        STRINGS[key + '_DESC'] = BRIEFS[mission - 1]
        write_resource(ROOT / f'content/missions/campaign_{mission:02}.tres', 'MissionDefinition', f'campaign.{mission:02}', key,
                       f'campaign_index = {mission}\nprototype = false\nwave_ids = {names(wave_ids)}')
    lines = ['class_name EncounterWaves', 'extends RefCounted', '## Generated by tools/generate_encounter_content.py.', 'const MISSIONS: Dictionary = {']
    for mission in range(1, 4):
        lines.append(f'\t{mission}: [')
        lines.extend(f'\t\tpreload("res://content/encounters/waves/m{mission:02}_w{wave:02}.tres"),' for wave in range(1, 11))
        lines.append('\t],')
    lines.append('}')
    (ROOT / 'scripts/campaign/encounter_waves.gd').write_text('\n'.join(lines) + '\n')
    p = ROOT / 'assets/ui_strings.csv'
    rows = list(csv.reader(io.StringIO(p.read_text())))
    keys = {row[0]: i for i, row in enumerate(rows) if row}
    for key, value in STRINGS.items():
        if key in keys:
            rows[keys[key]] = [key, value]
        else:
            rows.append([key, value])
    buf = io.StringIO()
    csv.writer(buf, lineterminator='\n').writerows(rows)
    p.write_text(buf.getvalue())
    print('Generated three authored missions, 30 waves, and three family elites.')

if __name__ == '__main__':
    generate()
